### ISSUE TITLE
Quick Simple Editor - Incompatible with MariaDB 10.2.4 and newer versions

### ISSUE THREAD

**Issue by EHRA1** [martec/quicksmpeditor#1]
Português:

Olá martec, inicialmente, muito obrigado por desenvolver o Quick Simple Editor. Ele é o melhor editor que há para a resposta rápida. Infelizmente, ele é incompatível com MariaDB 10.2.4 e versões mais recentes. O problema ocorre porque a palavra "rows" está como palavra chave reservada para MariaDB desde a versão 10.2.4. Eu consegui fazer a correção editando o "quicksmpeditor.php". Eu alterei "rows" por outra palavra e o problema foi corrigido. Eu não sou um programador avançado, mas parece que essa alteração é o suficiente para corrigir a incompatibilidade do Quick Simple Editor com as versões mais recentes do MariaDB. 

Abraço e obrigado por desenvolver plugins tão legais para o MyBB.

_______________________________________________________________________________________________________________
English:

Hello Martec, initially thank you very much for developing the Quick Simple Editor. He is the best editor there is for quick response. Unfortunately, it is incompatible with MariaDB 10.2.4 and newer versions. The problem occurs because the word "rows" is as keyword reserved for MariaDB since version 10.2.4. I was able to do the fix by editing the "quicksmpeditor.php". I changed "rows" by another word and the problem was corrected. I am not an advanced programmer, but it looks like this change is enough to correct the incompatibility of Quick Simple Editor with the newer versions of MariaDB.

Hugs and thanks for developing such cool plugins for MyBB.

**Comment by martec** [comment]
fixed in 1.1.1
